version: '2'
services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro

  whoami:
    image: jwilder/whoami
    container_name: whoami
    environment:
      - VIRTUAL_HOST=whoami.local

  dong:
    image: jwilder/whoami
    container_name: test
    environment:
      - VIRTUAL_HOST=test.local

networks:
  default:
    external:
      name: nginx-proxy
