version: '2'
services:
  nginx-proxy:
    build: .
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    environment:
      - CERT_VIRTUAL_HOST=boson.dev.local
      - CERT_PASSWORD=mySup3rS3cr3tP4ssword
      - CERT_SUBJ=/C=FI/ST=Uusimaa/L=Espoo/O=Fake Company/CN=*.boson.dev.local
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro

  whoami:
    image: jwilder/whoami
    container_name: whoami
    environment:
      - VIRTUAL_HOST=whoami.boson.dev.local

  test:
    image: jwilder/whoami
    container_name: test
    environment:
      - VIRTUAL_HOST=test.boson.dev.local

networks:
  default:
    external:
      name: nginx-proxy
